services:
  gm_app:
    image: gm_app_image:1.0
    build:
      context: ./gm_app
    container_name: gm_app_container
    ports:
      - '8585:8080'
    volumes:
      - ./gm_app:/app
    networks:
      - gm_backend

  celery_worker:
    build:
      context: ./gm_app
    container_name: celery_worker_container
    volumes:
      - ./gm_app:/app
    command: celery -A app.celery_worker.tasks worker --loglevel=info
    depends_on:
      - redis-server
    networks:
      - gm_backend

  angu_app:
    image: angu_app_image:1.0
    build:
      context: ./frontend
    container_name: angu_app_container
    ports:
      - '4200:4200'
    networks:
      - gm_backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  redis-server:
    image: redis:7.0
    container_name: redis_server_container
#    ports:
#      - "6370:6379"
    restart: always
    networks:
      gm_backend:


  sample_api:
    image: sample_api_image:1.0
    build:
      context: ./sample-api
    container_name: sample-api_container
    ports:
      - '3000:3000'
    networks:
      - gm_backend



networks:
  gm_backend:
