services:
  gm_app:
    image: gm_app_image:1.0
    build:
      context: ./gm_app
    container_name: gm_app_container
    volumes:
      - ./gm_app:/app
    networks:
      - gm_backend

  angu_app:
    image: angu_app_image:1.0
    build:
      context: ./frontend
    container_name: angu_app_container
    ports:
      - '4200:4200'
    networks:
      - gm_backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  celery_worker:
    build:
      context: ./gm_app
    container_name: celery_worker_container
    volumes:
      - ./gm_app:/app
    command: celery -A app.celery_worker.tasks worker --loglevel=info
    depends_on:
      - redis-server
    networks:
      - gm_backend

  redis-server:
    image: redis:7.0
    container_name: redis_server_container
    restart: always
    networks:
      gm_backend:


  sample_api:
    image: sample_api_image:1.0
    build:
      context: ./sample-api
    container_name: sample-api_container
    networks:
      - gm_backend

  nginx:
    image: nginx:1.21
    container_name: nginx_container
    ports:
      - '9090:80'
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist/angu-app/browser:/usr/share/nginx/html/
    depends_on:
      - gm_app
      - angu_app
    networks:
      - gm_backend

networks:
  gm_backend:
